apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tdc-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: api.thedabbacompany.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tdc-backend
                port:
                  number: 3000
    - host: admin.thedabbacompany.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tdc-admin-dashboard
                port:
                  number: 3001
    - host: partner.thedabbacompany.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tdc-partner-dashboard
                port:
                  number: 3002
